artifact_location: file:e:/IBA_MS_DS 2026/Computer Vision/Project/New folder/runs/mlflow/0
creation_time: 1761844716158
experiment_id: '0'
last_update_time: 1761844716158
lifecycle_stage: active
name: Default
